import { NextResponse } from "next/server";

export async function POST(request: Request) {
  try {
    const data = await request.formData();
    const file = data.get("file") as File | null;
    const topic = data.get("topic") as string | null;

    if (!file && !topic) {
      return NextResponse.json(
        { error: "Please provide either a topic or upload a syllabus file." },
        { status: 400 }
      );
    }

    let extractedText = "";

    // If a file was uploaded, extract its text (simulated for now, can be replaced with actual PDF/Doc parsing)
    if (file) {
      console.log(`Received file: ${file.name}, size: ${file.size} bytes`);
      // In a real scenario, you'd use a library like pdf-parse for PDFs or mammoth for DOCX.
      // Here we simulate extracting text.
      extractedText = `Simulated extracted text from ${file.name}. `;
    }

    if (topic) {
      extractedText += `User wants to focus on topic: ${topic}.`;
    }

    // Call your AI Model here (e.g., IBM Granite, OpenAI, or Gemini)
    // Simulated AI response generating courses and concepts
    const generatedCourse = {
      title: topic ? `Mastering ${topic}` : "Advanced Course based on Syllabus",
      description: "This course was dynamically generated by analyzing your inputs and syllabus.",
      modules: [
        {
          id: 1,
          title: "Introduction & Core Concepts",
          duration: "2 weeks",
          concepts: [
            "Foundations of the topic",
            "Key terminology",
            "Historical context",
          ],
        },
        {
          id: 2,
          title: "Intermediate Applications",
          duration: "3 weeks",
          concepts: [
            "Practical implementations",
            "Analyzing case studies",
            "Problem-solving techniques",
          ],
        },
        {
          id: 3,
          title: "Advanced Mastery & Project",
          duration: "4 weeks",
          concepts: [
            "Complex architectural patterns",
            "Performance optimization",
            "Final capstone project",
          ],
        },
      ],
      suggestedResources: ["Resource A", "Resource B", "Resource C"],
    };

    // Simulate AI processing delay
    await new Promise((resolve) => setTimeout(resolve, 2000));

    return NextResponse.json({
      success: true,
      message: "Course generated successfully",
      course: generatedCourse,
    });
  } catch (error) {
    console.error("Error generating course:", error);
    return NextResponse.json(
      { error: "Failed to generate course. Please try again." },
      { status: 500 }
    );
  }
}
